name: Python CI
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ghas-github-pulumi-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python-ci:
    uses: srendipity-lab/github-pulumi/.github/workflows/reusable-python-ci.yml@main
